twig:
    file_name_pattern: '*.twig'
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - 'form/my_form_theme.html.twig'

when@test:
    twig:
        strict_variables: true
