vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        scenario_image:
            uri_prefix: /uploads/scenarios
            upload_destination: '%kernel.project_dir%/public/uploads/scenarios'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
