
services:
###> doctrine/doctrine-bundle ###
  frankenphp:
    build: .
    container_name: frankenphp
    depends_on:
      - database
    ports:
      - 8081:80
    volumes:
      - .:/var/www/html
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - database
    restart: unless-stopped
    ports:
      - 8888:80
    environment:
      MYSQL_ROOT_PASSWORD: MySecretPassword
      PMA_HOST: database

volumes:
###> doctrine/doctrine-bundle ###
  database_data:

###< doctrine/doctrine-bundle ###
