name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: forgequest_db_test
          MYSQL_USER: user_test
          MYSQL_PASSWORD: password_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Configure .env.test
        run: |
          echo "DATABASE_URL=mysql://user_test:password_test@127.0.0.1:3306/forgequest_db?serverVersion=8.0.32&charset=utf8mb4" > .env.test

      - name: Run Doctrine migrations
        env:
          KERNEL_CLASS: "App\Kernel"
        run: ./bin/console doctrine:migrations:migrate --env=test --no-interaction

      - name: Run fixtures
        env:
          KERNEL_CLASS: "App\Kernel"
        run: ./bin/console doctrine:fixtures:load --env=test --no-interaction

      - name: Run PHPUnit tests
        env:
          KERNEL_CLASS: "App\Kernel"
          DATABASE_URL: mysql://user_test:password_test@127.0.0.1:3306/forgequest_db?serverVersion=8.0.32&charset=utf8mb4
        run: ./bin/phpunit tests

      - name: Run PHPstan
        run: ./vendor/bin/phpstan analyze

      - name: Run PHP-CS-Fixer (lint)
        run: ./vendor/bin/php-cs-fixer fix --diff --dry-run --allow-risky=yes
